### ISSUE TITLE
Registration

### ISSUE THREAD

**Issue by lippertmarkus** [lippertmarkus/dhbw-project#12]
WXC_010

09.06.16 - 16.06.16

**Beschreibung**
Ein Benutzer kann sich über ein HTML-Formular schnell und einfach registrieren. Dabei müssen mindestens "Benutzername", "Kennwort" und "Email-Adresse" angegeben werden. Das Passwort wird innerhalb der Datenbank mit einem sicheren Algorithmus verschlüsselt. Bei Absenden des Formulars werden die Daten an den Server übergeben, von PHP überprüft und in eine Datenbank übertragen. Anschließend wird eine E-Mail an den neuen Benutzer versandt, in welcher ein Link enthalten ist, über den er sein Benutzerkonto vor Anmeldung zuerst aktivieren muss.	 

**Wechselwirkungen**
Die Funktion benötigt Zugriff auf die MySQL-Datenbank und den SMTP-Server für den Mailversandt.

**Risiken**
Bei der Registrierung muss geprüft werden, ob die E-Mail-Adresse noch nicht im System vorhanden ist. Trotz dieser Prüfung besteht ein Risiko, dass sich eine einzelne Person mit verschiedenen E-Mail-Adressen mehrfach registriert. Das Passwort muss verschlüsselt in der Datenbank gespeichert werden, sodass dieses bei einem eventuellen Angriff auf das Datenbanksystem nicht einfach ausgelesen werden kann.

**Testhinweise**
Getestet werden muss, dass Benutzernamen bei der Registrierung nicht mehrfach verwendet werden können. Das HTML-Formular muss auf Sicherheit gegen XSS-Attacken und SQL-Injections getestet werden.

**Comment by Hackyy** [comment]
#33 fixed?
