### ISSUE TITLE
Product/Service overview

### ISSUE THREAD

**Issue by lippertmarkus** [lippertmarkus/dhbw-project#20]
WXC_110

21.06.16 - 28.06.16

**Beschreibung**
Auf einer Übersichtsseite kann der Benutzer sich alle Produkte und Dienstleistungen mit den nötigen Informationen (Benutzerbewertung, Kosten, usw.) anschauen. Durch Aufrufen eines Eintrags werden alle Informationen aus der Datenbank über diesen angezeigt. Zudem kann hier über einen Schalter der Bestellprozess angestoßen werden. Die Informationen werden via PHP aus der Datenbank bezogen und im Browser dargestellt.

**Wechselwirkungen**
Es wird Zugriff auf die Datenbank benötigt. Der Bestellprozess wird verwendet.

**Risiken**
Es dürfen keine bereits beendeten Dienstleistungen angezeigt werden.

**Testhinweise**
Hierbei muss das Erstellen und Kaufen eines Produkts/einer Dienstleistung getestet werden.

**Comment by Hackyy** [comment]
@Hansium 
SELECT product.id, product.title, user.username FROM product 
LEFT JOIN user on product.user_id = user.id
where product.archived = 0;
